# Epic todo app
# This is a test for file writing, file creating and app configs
# Also because this is just a classic compsci bullying assignment and I like
# bullying compsci majors

PROCESS_NAME=todo
LINK_TYPE=dynamic
LIBRARIES:=

include ../user.mk
