# lsdk.lib is a software development kit built on top of the lightos.lib core library
#
# Where lightos.lib provides core utilities to interact with objects, talk with drivers, has libc built in, ect. lsdk.lib focusses more on the utilities
# needed to build basic userspace applications, like basic datastructures, abstraction layers, ect. Of course we're still in beautiful C-land, but this
# library simply makes sure that trivial parts of any application dont need to be rewritten per application.

LIBRARY_NAME=lsdk
LINKTYPE=dynamic
LIBRARIES=

include ../library.mk
