
#ifndef __ANIVA_KTERM_FONT__
#define __ANIVA_KTERM_FONT__

#define KTERM_HLINE_GLYPH 0x01
#define KTERM_VLINE_GLYPH 0x02
#define KTERM_RT_CORNER_GLYPH 0x03
#define KTERM_LT_CORNER_GLYPH 0x04
#define KTERM_RB_CORNER_GLYPH 0x05
#define KTERM_LB_CORNER_GLYPH 0x06

#define KTERM_CURSOR_GLYPH 127

// extern char font8x8_basic[128][8];

#endif // !__ANIVA_KTERM_FONT__
