#ifndef __ANIVA_PCI_DEFINITIONS__
#define __ANIVA_PCI_DEFINITIONS__

// TODO: more
typedef enum {
  IO,
  IOMEM16BIT,
  IOMEM32BIT,
  IOMEM64BIT,
} BridgeAccessType_t;

typedef enum {
  NO_CODE = 0x00,
  MASS_STORAGE = 0x01,
  NETWORK_CONTROLLER = 0x02,
  DISPLAY_CONTROLLER = 0x03,
  MULTIMEDIA = 0x04,
  MEMORY_CONTROLLER = 0x05,
  BRIDGE_DEVICE = 0x06,
  SIMPLE_COMMUNICATIONS_CONTROLLER = 0x07,
  BASE_SYSTEM_PERIPHERAL = 0x08,
  INPUT_DEVICE = 0x09,
  DOCKING_STATION = 0x0A,
  PROCESSOR = 0x0B,
  SERIAL_BUS_CONTROLLER = 0x0C,
  WIRELESS_CONTROLLER = 0x0D,
  INTELLIGENT_IO_CONTROLLER = 0x0E,
  SATELLITE_COMMUNICATIONS_CONTROLLER = 0x0F,
  ENCRYPT_DECRYPT_CONTROLLER = 0x10,
  DATA_ACQUISITION_SIGNAL_PROCESSING_CONTROLLER = 0x11,
  PROCESSING_ACCELERATOR = 0x12,
  NON_ESSENTIAL_INSTRUMENTATION = 0x13,
  NO_CLASS = 0xff
} pci_class_id_t;

typedef enum {
  IDE_C = 0x01,
  SATA_C = 0x06,
  NVMe_C = 0x08,
} MassstorageSubClasIDType_t;

#endif // !__ANIVA_PCI_DEFINITIONS__
